% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Dec-2023 12:02:21
%  MATLAB version: 23.2.0.2428915 (R2023b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('part4_0pt920kg.mat');

curr = saveVarsMat.curr; % <322x4 double> too many elements

i = 105.60000000000001;

loop = 1;

maxVel = 44;

maxVel_deg = 264;

pos = saveVarsMat.pos; % <322x4 double> too many elements

readings = ...
  [-45 -3.779296875 25.13671875 -18.896484375;
   0 61.83 65.952 0;
   -2.69 -349.7 104.91 -86.08];

robot = saveVarsMat.robot; % <1x1 Robot> unsupported class

travelTime = 0.5;

vel = saveVarsMat.vel; % <322x4 double> too many elements

vel_waypoints = [-264 -211.20000000000002 158.4 105.60000000000001];

clear saveVarsMat;
